services:  
  php:
    build:
      dockerfile: php7-apache-dockerfile
      context: .
    container_name: meu-php-4
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - /home/thiago/Desktop/docker-tests/apache-php-mysql-4:/var/www/html
    links:
      - db

  db:
    image: mysql:latest
    restart: always
    container_name: meu-mysql-4    
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=testando_docker_4      
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"       
      